### PR TITLE
Fix bug where opponent doesn't find out unit is dead

### PR DESCRIPTION
**Pull request by baconpat**
Seems to be related to a unit that's still moving but is killed before the moevement fully complete's (or something like that). The "fix", without fully understanding the problem, is to mark both both tiles (previous and current) for the killed unit as dirty, so the killing player will be sure to get the message that the unit is dead.

Otherwise the killing player thinks there's an invincible non-moving unit hanging out on a tile forever.

### CODE REVIEW

**Comment by BrianMay-AO** [comment]
I might have merged this too soon.
When I ran my client against it I got a server crash :grimacing:

**Comment by shawn42** [comment]
For what it's worth, I was able to run the server w/ my custom client as well as the ruby sdk.

**Comment by baconpat** [comment]
I think @BrianMay-AO determined the bug I introduced was when a tank tries to SHOOT. I've never tried a tank so I never tested that part out - apparently the code is slightly different in the SHOOT and MELEE so my copy/paste to apply the change in both places (without really reading it through) wasn't ideal. 😬 We're going to do some testing tomorrow and get it fixed.

**Comment by BrianMay-AO** [comment]
I rolled back the shoot portion of this fix temporarily just to prevent the server crash. We'll look into what we can do about the bug tomorrow.

**Pull request merged**
